services:
  node_exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    network_mode: host
    pid: host
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
