---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ prometheus_app_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Render docker-compose.yml and prometheus.yml from templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ prometheus_app_path }}/{{ item }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - docker-compose.yml
    - prometheus.yml

- name: Restart container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_app_path }}"
    remove_orphans: true
    recreate: always
    pull: always
