---
- name: Uninstall deprecated packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
    state: absent

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u=rw,g=r,o=r

- name: Get Ubuntu architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_arch
  changed_when: false

- name: Get Ubuntu codename
  ansible.builtin.shell: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  register: docker_ubuntu_codename
  changed_when: false

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb
      [arch={{ docker_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ docker_ubuntu_codename.stdout }}
      stable
    filename: docker
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Run docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
