---
- name: Create volume mount directory
  ansible.builtin.file:
    path: "{{ traefik_app_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Render docker-compose.yml and traefik.yml from templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ traefik_app_path }}/{{ item }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - docker-compose.yml
    - traefik.yml

- name: Start the container
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_app_path }}"
