---
- name: Deploy a specific role to all hosts
  hosts: cloud_ru
  become: true
  tasks:
    - name: Include the specified role
      ansible.builtin.include_role:
        name: "{{ role_to_deploy }}"
