---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ bio_app_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Render docker-compose.yml from template
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ bio_app_path }}/docker-compose.yml"
    mode: "u=rw,g=r,o=r"

- name: Start the container
  community.docker.docker_compose_v2:
    project_src: "{{ bio_app_path }}"
