name: Ansible files & Deployment

on:
  push:
    paths:
      - 'inventory/**'
      - 'playbooks/**'
      - 'roles/**'
  pull_request:
    paths:
      - 'inventory/**'
      - 'playbooks/**'
      - 'roles/**'

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p'

    # uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    # with:
    #   args: '-p playbooks'
