name: Ansible files & Deployment

on:
  push:
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible + Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Install required Ansible collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Run ansible-lint
        run: |
          ansible-lint
