name: Deploy a single role

on:
  repository_dispatch:
    types: [Deploy a single role]
  workflow_dispatch:
    inputs:
      role:
        description: 'Ansible role to deploy'
        required: true

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.role || github.event.client_payload.role }}
    runs-on: ubuntu-latest
    environment: production
    env:
      ROLE: ${{ github.event.inputs.role || github.event.client_payload.role }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ansible
          ANSIBLE_HOST_KEY_CHECKING: False
        run: >-
          ansible-playbook
          -e "role_to_deploy=${{ env.ROLE }}"
          -e "gh_username=${{ github.repository_owner }}"
          -e "ghcr_token=${{ secrets.GHCR_TOKEN }}"
          --private-key private_key.pem
          playbooks/deploy_role.yml
